mysite/mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^where_to_eat/', include('where_to_eat.urls', namespace="where_to_eat")),
)

mysite/where_to_eat/urls.py
from django.conf.urls import patterns, url

from where_to_eat import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    
    url(r'^create_ballot/$', views.create_ballot, name='create_ballot'),
    url(r'^create_ballot_submit/$', views.create_ballot_submit, name='create_ballot_submit'),

    url(r'^delete_confirmation/(?P<ballot_id>\d+)/$', views.delete_confirmation,
        name='delete_confirmation'),
    url(r'^delete_ballot/(?P<ballot_id>\d+)/$', views.delete_ballot, name='delete_ballot'),
        
    url(r'^(?P<ballot_id>\d+)/$', views.ballot, name='ballot'),
    url(r'^(?P<ballot_id>\d+)/sign_in/$', views.sign_in, name='sign_in'),
    url(r'^(?P<ballot_id>\d+)/add_option/$', views.add_ballot_option, name='add_ballot_option'),
    url(r'^(?P<ballot_id>\d+)/get_options/$', views.get_ballot_options, name='get_ballot_options'),
    url(r'^(?P<ballot_id>\d+)/submit_ballot/$', views.submit_ballot, name='submit_ballot'),
    url(r'^(?P<ballot_id>\d+)/results/$', views.results, name='results'),
    
)

mysite/where_to_eat/models.py
from django.db import models

class Ballot(models.Model):
    date = models.DateTimeField('date')
    voting_method = models.CharField(max_length=200, default='plurality_voting')
    winner = models.CharField(max_length=200, default='')
    
    def __unicode__(self):
        return str(self.date)
    
class Restaurant(models.Model):
    ballot = models.ForeignKey(Ballot)
    name = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __unicode__(self):
        return self.name
        
class Voter(models.Model):
    ballot = models.ForeignKey(Ballot)
    name = models.CharField(max_length=200)
    votes_submitted = models.IntegerField(default=0)

    def __unicode__(self):
        return self.name

mysite/where_to_eat/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.core.exceptions import ObjectDoesNotExist

import simplejson
import random

from django.views.decorators.csrf import csrf_exempt

from where_to_eat.models import Ballot, Restaurant, Voter

def index(request):
    ballot_list = Ballot.objects.order_by('-date')
    context = {'ballot_list': ballot_list}
    return render(request, 'where_to_eat/index.html', context)
    
def create_ballot(request):
    return render(request, 'where_to_eat/create_ballot.html', {})

def create_ballot_submit(request):
    b = Ballot(date=timezone.now())
    b.voting_method = request.POST['voting_system']
    b.save()
    return HttpResponseRedirect(reverse('where_to_eat:index'))

def delete_confirmation(request, ballot_id):
    ballot = get_object_or_404(Ballot, pk=ballot_id)
    return render(request, 'where_to_eat/delete_confirmation.html', {'ballot': ballot})

def delete_ballot(request, ballot_id):
    ballot = get_object_or_404(Ballot, pk=ballot_id)
    ballot.delete()
    return HttpResponseRedirect(reverse('where_to_eat:index'))

def sign_in(request, ballot_id):
    ballot = get_object_or_404(Ballot, pk=ballot_id)
    return render(request, 'where_to_eat/sign_in.html', {'ballot': ballot})


def ballot(request, ballot_id):
    ballot = get_object_or_404(Ballot, pk=ballot_id)
    
    try:
        username = request.POST['username']        
        context = {'ballot': ballot, 'username': username}
        return render(request, 'where_to_eat/ballot.html', context)
        
    # redirect to sign in page if they didn't just sign in
    except (KeyError, Voter.DoesNotExist):
        return HttpResponseRedirect(reverse('where_to_eat:sign_in', args=(ballot_id,)))

@csrf_exempt
def add_ballot_option(request, ballot_id):
    ballot = get_object_or_404(Ballot, pk=ballot_id)
    
    response = {'repeat': False}
    
    try:
        restaurant_name = request.POST['restaurant_name']
        if ballot.restaurant_set.filter(name=restaurant_name).count() == 0:
            ballot.restaurant_set.create(name=restaurant_name)
        else:
            response['repeat'] = True
    except (KeyError):
        pass
    
    return HttpResponse(simplejson.dumps(response), content_type='application/json')


def get_ballot_options(request, ballot_id):
    ballot = get_object_or_404(Ballot, pk=ballot_id)
    response = {'restaurants': []}
    for restaurant in ballot.restaurant_set.all():
        response['restaurants'].append(restaurant.name)
    return HttpResponse(simplejson.dumps(response), content_type='application/json')

@csrf_exempt
def submit_ballot(request, ballot_id):
    ballot = get_object_or_404(Ballot, pk=ballot_id)
    
    response = {'already_submitted': False}
    
    try:
        username = request.POST['username']
        
        # if ballot already has a voter of the same name, do not count
        if ballot.voter_set.filter(name=username).count() == 1:
            response['already_submitted'] = True
            
        # otherwise, adjust database
        else:
            voter = ballot.voter_set.create(name=username)
            
            for item in request.POST:
                # restaurant POST data will start with 'restaurant:'
                if item.startswith('restaurant:'):
                    restaurant_name = item.replace('restaurant:', '', 1)
                    votes = int(request.POST[item])
                    restaurant = ballot.restaurant_set.get(name=restaurant_name)
                    restaurant.votes += votes
                    restaurant.save()
                    voter.votes_submitted += votes

            voter.save()      
                
            if voter.votes_submitted > 0 and ballot.voting_method == 'probabilistic_voting':
                save_new_probabilistic_winner(ballot)
    
    # if there's no POST data, redirect to sign-in page
    except (KeyError):
        return HttpResponseRedirect(reverse('where_to_eat:sign_in', args=(ballot_id,)))

    return HttpResponse(simplejson.dumps(response), content_type='application/json')

def save_new_probabilistic_winner(ballot):
    total_votes = 0
    for restaurant in ballot.restaurant_set.all():
        total_votes += restaurant.votes
    
    if total_votes > 0:
        r = random.randint(1, total_votes)
        votes = 0
        for restaurant in ballot.restaurant_set.all():
            votes += restaurant.votes
            if r <= votes:
                ballot.winner = restaurant.name
                ballot.save()
                break
    

def results(request, ballot_id):
    ballot = get_object_or_404(Ballot, pk=ballot_id)
    
    total_votes = {} # dictionary with mappings like {'Chipotle', 5}
    for restaurant in ballot.restaurant_set.all():
        total_votes[restaurant.name] = restaurant.votes
    
    # sorted list of tuples, e.g. [('Chipotle', 5), ('Pizza Hut', 4)]
    sorted_by_votes = sorted(total_votes, key=total_votes.get, reverse=True)
    for i in range(len(sorted_by_votes)):
        sorted_by_votes[i] = (sorted_by_votes[i], total_votes[sorted_by_votes[i]])
    
    voters = [] # list of all voters
    for voter in ballot.voter_set.all():
        voters.append(voter.name)
    
    winners = []
    
    if ballot.voting_method == 'plurality_voting':
        for restaurant in sorted_by_votes:
            if restaurant[1] == sorted_by_votes[0][1]:
                winners.append(restaurant[0])
            else:
                break
    
    elif ballot.voting_method == 'probabilistic_voting' and ballot.winner != '':
        winners.append(ballot.winner)
    
    context = {
        'ballot': ballot,
        'winners': winners,
        'sorted_by_votes': sorted_by_votes,
        'voters': voters,
    }
    
    return render(request, 'where_to_eat/results.html', context)

mysite/where_to_eat/templates/where_to_eat/ballot.html
<script src='http://code.jquery.com/jquery-1.8.3.js'></script>
<script>
    
    /*
     * Adds a new restaurant to the displayed list.
     */
    function add_list_item(restaurant_name) {
    	var $new_item = $( "<li><input type='button' class='add_vote' value='+'> <input type='button' class='remove_vote' value='-'> <b class='num_votes'>0</b> - <font class='restaurant_option'>" + restaurant_name + "</font></li>" );
        $( "#restaurant_list" ).append( $new_item );
  	    $( ".add_vote" ).last().click(click_add_button);
  	    $( ".remove_vote" ).last().click(click_remove_button);
    }
    
    /*
     * Adds a new restaurant to the database and to the displayed list.
     */
    function add_restaurant(restaurant_name) {
        $.ajax ({
            type: 'POST',
			dataType: 'json',
			url: "{% url 'where_to_eat:add_ballot_option' ballot.id %}",
			data: {restaurant_name : restaurant_name},
			success: function (data) {
                add_list_item(restaurant_name);
			},
			
			error: function() {
			    alert('Error adding restaurant :(')
			}
		});
    }
    
    function submit_ballot() {
        var submit_data = {'username': '{{ username }}'};
        for (var i = 0; i < $( ".restaurant_option" ).length; i++) {
            var $restaurant = $( ".restaurant_option" ).eq(i);
            var num_votes = $restaurant.siblings( ".num_votes" ).text();
            submit_data["restaurant:" + $restaurant.text()] = num_votes;
        }
        
        $.ajax ({
            type: 'POST',
            dataType: 'json',
            url: "{% url 'where_to_eat:submit_ballot' ballot.id %}",
            data: submit_data,
            success: function (data) {
                if (data['already_submitted']) {
                    $( "#already_voted" ).show(); 
                } else {
                    window.location.href = "{% url 'where_to_eat:results' ballot.id %}";
                }
            },
            error: function () {
                alert("Error sending votes :(");
            }
        });
    }
    
    /*
     * Requests a list of all the added restaurants and adds any new
     * ones to the displayed list.
     */
    function update_restaurants() { 
        $.ajax({
            type: 'GET',
            dataType: 'json',
            url: "{% url 'where_to_eat:get_ballot_options' ballot.id %}",
            data: {},
            success: function (data) {
                for (var i = 0; i < data['restaurants'].length; i++) {
                    var restaurant_name = data['restaurants'][i];
                    var already_there = false;
                    
                    for (var j = 0; j < $( ".restaurant_option" ).length; j++) {
                        var existing_option = $( ".restaurant_option" ).eq(j).text();
                        if ( restaurant_name === existing_option ) {
                            already_there = true;
                            break;
                        }
                    }
                    
                    if ( !already_there ) {
                        add_list_item( restaurant_name );
                    }
                }
            },
            
            error: function() {
                alert('Error retrieving restaurants :(')
            }
        });
  	}
    
    /*
     * Function that's called when a '+' button is clicked.
     */
    function click_add_button() {
        var $remaining = $( "#remaining_votes" );
      	        
        // if there are remaining votes, add a vote to corresponding label
        if ( Number($remaining.text()) > 0 ) {
            var $num_votes = $(this).siblings( ".num_votes" );
                    
            $num_votes.text( Number($num_votes.text()) + 1 );
            $remaining.text( Number($remaining.text()) - 1 );
        }
    }
    
    /*
     * Function that's called when a '-' button is clicked.
     */
    function click_remove_button() {
        var $num_votes = $(this).siblings( ".num_votes" );
        
        // if corresponding label has votes, remove one
        if ( Number($num_votes.text()) > 0) {
            var $remaining = $( "#remaining_votes" );

            $num_votes.text( Number($num_votes.text()) - 1 );
            $remaining.text( Number($remaining.text()) + 1 );
        }
    }
    
  	$(document).ready(function () {
  	
  	    $( "#add_restaurant" )
  	        .click(function(){
  	            if ( $( "#restaurant_name" ).val() ) {
  	                add_restaurant( $( "#restaurant_name" ).val() );
  	                $( "#restaurant_name" ).val("");
  	            }
  	        });
  	
  	    $( ".add_vote" ).click(click_add_button);
        
  	    $( ".remove_vote" ).click(click_remove_button);
  	    
  	    $( "#submit_ballot" ).click(submit_ballot);

        // repeatedly check for updated restaurants
        update_restaurants();
  	    setInterval(update_restaurants, 2000);

    })
    
</script>

<h1 align="center">{{ ballot.date }}</h1>

<p align="center">
<font size=4>
    Signed in as <b>{{ username }}</b> <br />
    Available votes: <b id="remaining_votes">10</b>
    <font id="already_voted" color="red" hidden><br/><b>You already voted on this ballot.</b></font>
</font>
</p>

<form method="POST">
{% csrf_token %}

<input style="display:none" name="username" value="{{ username }}">


<input type="text" id="restaurant_name" />
<input type="button" id="add_restaurant" value="Add restaurant" />

<br/>
<br/>
<u1 id="restaurant_list"></u1>
<br/>

<input type="button" id="submit_ballot" value="Submit ballot" />

</form>

mysite/where_to_eat/templates/where_to_eat/create_ballot.html
<h1 align="center">Create new ballot</h1>

<form action="{% url 'where_to_eat:create_ballot_submit' %}" method="post">
{% csrf_token %}

<h3>Voting style</h3>
<input type="radio" name="voting_system" value="plurality_voting" id="plurality_voting" checked required>
<label for="plurality_voting">
Plurality voting
<i><font color="gray">
(the restaurant with the most votes wins)
</font></i>
</label><br/>

<input type="radio" name="voting_system" value="probabilistic_voting" id="probabilistic_voting" >
<label for="probabilistic_voting">
Probabilistic voting
<i><font color="gray">
(a restaurant's chance of winning is proportional to its number of votes)
</font></i>
</label><br/>

<br/>
<input type="submit" value="Submit" />
</form>

mysite/where_to_eat/templates/where_to_eat/delete_confirmation.html
<h1 align="center">Are you sure you want to delete this ballot?</h1>

<form action="{% url 'where_to_eat:delete_ballot' ballot.id %}">
<input type="submit" value="YES" />
</form>

<form action="{% url 'where_to_eat:index' %}">
<input type="submit" value="NO" />
</form>

mysite/where_to_eat/templates/where_to_eat/index.html
<h1 align="center">Restaurant Ballots</h1>

<form action="{% url 'where_to_eat:create_ballot' %}">
<input type="submit" value="Create new ballot" />
</form>

{% if ballot_list %}
    <u1>
    {% for ballot in ballot_list %}
        <li>
            <a href="{% url 'where_to_eat:sign_in' ballot.id %}">{{ ballot.date }}</a>
            <a href="{% url 'where_to_eat:results' ballot.id %}">[Results]</a>
            <a href="{% url 'where_to_eat:delete_confirmation' ballot.id %}">[Delete]</a>
        </li>
    {% endfor %}
    </u1>
{% else %}
    <p>No ballots are available.</p>
{% endif %}

mysite/where_to_eat/templates/where_to_eat/results.html
<h1 align="center">Ballot results {{ ballot.date }}</h1>
<p align="center">Voting system:
{% if ballot.voting_method == "plurality_voting" %}
    Plurality voting
{% elif ballot.voting_method == "probabilistic_voting" %}
    Probabilistic voting
{% endif %}
</p>

<p align="center">
{% if winners|length == 0 %}
    No votes have been cast yet.
{% elif winners|length == 1 %}
    <font color="green" size="7"><b>Winner: {{ winners.0 }}</b></font>
{% else %}
    <font color="red" size="7">There was a tie between
    {% for winner in winners %}
        {% if forloop.last %}and
        {% elif not forloop.first %},
        {% endif %}
        {{ winner }}
    {% endfor %}
    .</b></font>
{% endif %}
</p>


<table border="1" align="center">
<tr>
<th>Restaurant</th><th># Votes</th>
</tr>

{% for restaurant in sorted_by_votes %}
    <tr>
    <td>{{ restaurant.0 }}</td><td>{{ restaurant.1 }}</td>
    </tr>
{% endfor %}
</table>

<p>
<table border="0" align="center">
<center>
<tr><th><u><font size="5">Voters:</u></font></th></tr> 
<td><ul>
{% for voter in voters %}
    <li>{{ voter }}
{% endfor %}
</ul></td>
</center>
</p>

mysite/where_to_eat/templates/where_to_eat/sign_in.html
<h1 align="center">Sign in to vote on this restaurant ballot</h1>


<form action="{% url 'where_to_eat:ballot' ballot.id %}" method="post">
{% csrf_token %}

<input align="center" type="text" name="username"><br />
<input align="center" type="submit" value="Sign in" />

</form>